#ifndef PS2AVRGB_LUIZRIBEIRO_CONFIG_H
#define PS2AVRGB_LUIZRIBEIRO_CONFIG_H

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 500

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_DELAY 0

#endif
